services:
  dearme-app:
    image: dearmeproject/dearme:dev-latest
    container_name: dearme-dev-app
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - dearme-net

  mysql:
    image: mysql:8.0
    container_name: dearme-dev-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dearme
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - dearme-net

networks:
  dearme-net:
    driver: bridge
