### develop 브랜치에 push 시, 개발 서버 자동 배포

name: CI/CD Dev

on:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout source
        uses: actions/checkout@v4

      - name: 2️⃣ Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: 3️⃣ Gradle Wrapper 권한 부여
        run: chmod +x gradlew

      - name: 3️⃣-1 Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 4️⃣ Build JAR
        run: ./gradlew clean build -x test

      - name: 5️⃣ Docker login
        uses: docker/login-action@v3
        with:
          username: eunseoo
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: 6️⃣ Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: eunseoo/dearme:latest

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: 4️⃣ SSH into Dev Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull eunseoo/dearme:latest
            
            EXISTING_CONTAINER_ID=$(sudo docker ps -q -f "publish=8080" -f "status=running")
            if [ ! -z "$EXISTING_CONTAINER_ID" ]; then
              sudo docker stop $EXISTING_CONTAINER_ID
              sudo docker rm $EXISTING_CONTAINER_ID
            fi

            EXISTING_CONTAINER_ID=$(sudo docker ps -q -f "publish=8080" -f "status=exited")
            if [ ! -z "$EXISTING_CONTAINER_ID" ]; then
              sudo docker rm $EXISTING_CONTAINER_ID
            fi
            
            sudo docker run -d \
            -p 8080:8080 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            --name dearme \
            eunseoo/dearme:latest
